# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


# Review.destroy_all
# CampsiteTagging.destroy_all
Tag.destroy_all
# Category.destroy_all
Campsite.destroy_all
User.destroy_all
Venue.destroy_all

# CREATE CITY TABLE
# venue1 = Venue.create(name: "Hong Kong" )
# venue2 = Venue.create(name: "San Francisco")
# venue3 = Venue.create(name: "Rocky Mountain")
# venue4 = Venue.create(name: "Mexico City")
# venue5 = Venue.create(name: "Machu Picchu")
# venue6 = Venue.create(name: "Tokyo")
# venue7 = Venue.create(name: "Mount Fuji")
# venue8 = Venue.create(name: "Barcelona")
# venue9 = Venue.create(name: "Dublin")

# CREATE USER TABLE
# u1 = User.create({:first_name=>"Alex", :last_name=>"Gutmann", :email=>"edgardo@raynorflatley.org", :password=>"198el8"})
# u2 = User.create({:first_name=>"Caleb", :last_name=>"Kris", :email=>"cristine@hansen.biz", :password=>"1ciovk"})
# u3 = User.create({:first_name=>"Heath", :last_name=>"McCullough", :email=>"meredith.koelpin@toyglover.biz", :password=>"s5g7oh"})
# u4 = User.create({:first_name=>"Carmen", :last_name=>"McClure", :email=>"maudie@doyle.name", :password=>"4zvp2e"})
# u5 = User.create({:first_name=>"Leon", :last_name=>"Gislason", :email=>"enrique_pouros@schmitt.biz", :password=>"uxnol0"})
# u6 = User.create({:first_name=>"Genny", :last_name=>"Davis", :email=>"meredith@mcdermottjohns.com", :password=>"59yh21"})
# u7 = User.create({:first_name=>"Hulda", :last_name=>"Durgan", :email=>"fritz_tillman@rice.com", :password=>"vik50y"})
# u8 = User.create({:first_name=>"Boris", :last_name=>"Quitzon", :email=>"rosanna.wunsch@hane.co", :password=>"jvq6m3"})
# u9 = User.create({:first_name=>"Leigh", :last_name=>"Crona", :email=>"wade@jast.com", :password=>"mwy2bx"})
# u10 = User.create({:first_name=>"Dorene", :last_name=>"Hettinger", :email=>"damion@haagpurdy.info", :password=>"zmgnev"})
# u11 = User.create({:first_name=>"Cody", :last_name=>"Schoen", :email=>"deandre@haley.name", :password=>"8yrw65"})
# u12 = User.create({:first_name=>"Yolonda", :last_name=>"Buckridge", :email=>"mike@schulist.com", :password=>"bdrp59"})
# u13 = User.create({:first_name=>"Oliver", :last_name=>"Casper", :email=>"loise.mertz@funk.com", :password=>"i6jjk7"})
# u14 = User.create({:first_name=>"Joann", :last_name=>"Veum", :email=>"gail@buckridge.org", :password=>"jss6y5"})
# u15 = User.create({:first_name=>"Adolfo", :last_name=>"Okuneva", :email=>"treena.kautzer@hintz.org", :password=>"ovkdok"})
# u16 = User.create({:first_name=>"Remedios", :last_name=>"Muller", :email=>"caaundra@swaniawskistehr.net", :password=>"qjj7rq"})
# u17 = User.create({:first_name=>"Elliott", :last_name=>"Medhurst", :email=>"abraham@hettinger.org", :password=>"swbe4j"})
# u18 = User.create({:first_name=>"Lee", :last_name=>"Collier", :email=>"cedric.heaney@stantonfadel.co", :password=>"irnxg6"})
# u19 = User.create({:first_name=>"Abram", :last_name=>"Fritsch", :email=>"danita.kuhlman@ziemann.io", :password=>"b8xjxn"})
# u20 = User.create({:first_name=>"Leena", :last_name=>"Gleichner", :email=>"cameron_oreilly@torphy.info", :password=>"h4j4v9"})
# u21 = User.create({:first_name=>"Wenona", :last_name=>"O'Connell", :email=>"krysten@mcdermott.name", :password=>"rm6k9t"})
# u22 = User.create({:first_name=>"Thaddeus", :last_name=>"Sawayn", :email=>"svetlana@kunzebecker.net", :password=>"5ayvzd"})
# u23 = User.create({:first_name=>"Isiah", :last_name=>"Dibbert", :email=>"liza@osinskischuster.biz", :password=>"g537v9"})
# u24 = User.create({:first_name=>"Gwenn", :last_name=>"Weimann", :email=>"arianna_wehner@kovacek.com", :password=>"o67sbc"})
# u25 = User.create({:first_name=>"Douglas", :last_name=>"Leuschke", :email=>"rubin@jacobsonklein.com", :password=>"0zbay4"})



# # CREATE CAMPSITE TABLE
# campsite1 = Campsite.create({:name=>"Ho Pui Campsite", :lat=>22.410399, :lng=>114.0719723, :campsite_type=>"CAMPING", :capacity=>1, :price=>125, venue_id: venue1.id })
# campsite2 = Campsite.create({:name=>"Shui Long Wo Campsite", :lat=>22.4026316, :lng=>114.27539, :campsite_type=>"CAMPING", :capacity=>13, :price=>83, venue_id: venue1.id })
# campsite3 = Campsite.create({:name=>"Nam Shan Campsite", :lat=>22.2535258, :lng=>113.985974, :campsite_type=>"CAMPING", :capacity=>10, :price=>64, venue_id: venue1.id })
# campsite4 = Campsite.create({:name=>"Hong Kong Scout Association Gilwell Campsite", :lat=>22.3594516, :lng=>114.2220891, :campsite_type=>"CAMPING", :capacity=>17, :price=>60, venue_id: venue1.id })
# campsite5 = Campsite.create({:name=>"Tai Tan Campsite", :lat=>22.4371604, :lng=>114.3334102, :campsite_type=>"CAMPING", :capacity=>16, :price=>83, venue_id: venue1.id })
# campsite6 = Campsite.create({:name=>"Tsin Yue Wan Campsite", :lat=>22.2090693, :lng=>113.8444677, :campsite_type=>"CAMPING", :capacity=>4, :price=>158, venue_id: venue1.id })
# campsite7 = Campsite.create({:name=>"Wan Tsai South Campsite", :lat=>22.4616576, :lng=>114.3425039, :campsite_type=>"CAMPING", :capacity=>9, :price=>69, venue_id: venue1.id })
# campsite8 = Campsite.create({:name=>"Man Cheung Po Campsite", :lat=>22.2299847, :lng=>113.8665983, :campsite_type=>"CAMPING", :capacity=>16, :price=>62, venue_id: venue1.id })
# campsite9 = Campsite.create({:name=>"Nga Ying Kok Campsite", :lat=>22.2382189, :lng=>113.8525732, :campsite_type=>"CAMPING", :capacity=>6, :price=>173, venue_id: venue1.id })
# campsite10 = Campsite.create({:name=>"Gilwell Campsite", :lat=>22.3593983, :lng=>114.2220955, :campsite_type=>"CAMPING", :capacity=>8, :price=>49, venue_id: venue1.id })
# campsite11 = Campsite.create({:name=>"Hong Kong Adventure Corps Campsite", :lat=>22.38349, :lng=>114.333584, :campsite_type=>"CAMPING", :capacity=>1, :price=>79, venue_id: venue1.id })
# campsite12 = Campsite.create({:name=>"Ngong Ping Campsite (Lantau)", :lat=>22.254975, :lng=>113.913944, :campsite_type=>"CAMPING", :capacity=>16, :price=>84, venue_id: venue1.id })
# campsite13 = Campsite.create({:name=>"Sam A Chung Campsite", :lat=>22.5069453, :lng=>114.2707689, :campsite_type=>"CAMPING", :capacity=>4, :price=>65, venue_id: venue1.id })
# campsite14 = Campsite.create({:name=>"Tai Long Wan Campsite", :lat=>22.2140922, :lng=>113.8758767, :campsite_type=>"CAMPING", :capacity=>19, :price=>62, venue_id: venue1.id })
# campsite15 = Campsite.create({:name=>"Lead Mine Pass Campsite", :lat=>22.4119832, :lng=>114.1581798, :campsite_type=>"CAMPING", :capacity=>4, :price=>83, venue_id: venue1.id })
# campsite16 = Campsite.create({:name=>"Lau Shui Heung Campsite", :lat=>22.4913917, :lng=>114.1670805, :campsite_type=>"CAMPING", :capacity=>13, :price=>77, venue_id: venue1.id })
# campsite17 = Campsite.create({:name=>"Tung Lung Chau Campsite", :lat=>22.2582641, :lng=>114.2954362, :campsite_type=>"CAMPING", :capacity=>9, :price=>139, venue_id: venue1.id })
# campsite18 = Campsite.create({:name=>"Saiyuen Camping Adventure Park", :lat=>22.1994648, :lng=>114.0195477, :campsite_type=>"CAMPING", :capacity=>1, :price=>124, venue_id: venue1.id })
# campsite19 = Campsite.create({:name=>"Yee Ting Campsite", :lat=>22.4061172, :lng=>114.3253545, :campsite_type=>"CAMPING", :capacity=>1, :price=>137, venue_id: venue1.id })
# campsite20 = Campsite.create({:name=>"Yuen Ng Fan (Nam Fung Wan) Campsite", :lat=>22.3778028, :lng=>114.3328681, :campsite_type=>"CAMPING", :capacity=>10, :price=>67, venue_id: venue1.id })
# campsite21 = Campsite.create({:name=>"Saiyuen Camping Adventure Park", :lat=>22.1994648, :lng=>114.0195477, :campsite_type=>"GLAMPING", :capacity=>1, :price=>117, venue_id: venue1.id })
# campsite22 = Campsite.create({:name=>"Mingle Farm", :lat=>22.4481502, :lng=>113.957464, :campsite_type=>"GLAMPING", :capacity=>7, :price=>179, venue_id: venue1.id })
# campsite23 = Campsite.create({:name=>"Welcome Beach", :lat=>22.2343434, :lng=>113.9501256, :campsite_type=>"GLAMPING", :capacity=>10, :price=>148, venue_id: venue1.id })
# campsite24 = Campsite.create({:name=>"Long Coast Seasports", :lat=>22.2340359, :lng=>113.9563289, :campsite_type=>"GLAMPING", :capacity=>12, :price=>157, venue_id: venue1.id })
# campsite25 = Campsite.create({:name=>"YHA Ngong Ping SG Davis Youth Hostel", :lat=>22.254897, :lng=>113.910324, :campsite_type=>"GLAMPING", :capacity=>3, :price=>109, venue_id: venue1.id })
# campsite26 = Campsite.create({:name=>"Hong Kong Adventure Corps Campsite", :lat=>22.38349, :lng=>114.333584, :campsite_type=>"GLAMPING", :capacity=>19, :price=>46, venue_id: venue1.id })
# campsite27 = Campsite.create({:name=>"Glampingland", :lat=>22.4481502, :lng=>113.957464, :campsite_type=>"GLAMPING", :capacity=>12, :price=>147, venue_id: venue1.id })
# campsite28 = Campsite.create({:name=>"Ngong Ping Campsite (Lantau)", :lat=>22.254975, :lng=>113.913944, :campsite_type=>"GLAMPING", :capacity=>18, :price=>126, venue_id: venue1.id })
# campsite29 = Campsite.create({:name=>"YHA Hong Kong", :lat=>22.3340752, :lng=>114.1636093, :campsite_type=>"GLAMPING", :capacity=>7, :price=>152, venue_id: venue1.id })
# campsite30 = Campsite.create({:name=>"Shap Long Campsite", :lat=>22.2383723, :lng=>113.9883531, :campsite_type=>"GLAMPING", :capacity=>6, :price=>156, venue_id: venue1.id })
# campsite31 = Campsite.create({:name=>"涌背營地 Chung Pui Campsite", :lat=>22.487418, :lng=>114.2429704, :campsite_type=>"GLAMPING", :capacity=>2, :price=>76, venue_id: venue1.id })
# campsite32 = Campsite.create({:name=>"東華三院馬草壟營地", :lat=>22.5114435, :lng=>114.0972025, :campsite_type=>"GLAMPING", :capacity=>9, :price=>179, venue_id: venue1.id })
# campsite33 = Campsite.create({:name=>"Sai Wan Campsite", :lat=>22.3988768, :lng=>114.3698364, :campsite_type=>"GLAMPING", :capacity=>15, :price=>133, venue_id: venue1.id })
# campsite34 = Campsite.create({:name=>"Rotary Club Campsite", :lat=>22.4049866, :lng=>114.1052295, :campsite_type=>"GLAMPING", :capacity=>14, :price=>95, venue_id: venue1.id })
# campsite35 = Campsite.create({:name=>"Jockey Club Mt. Davis Youth Hostel", :lat=>22.2773086, :lng=>114.1222068, :campsite_type=>"GLAMPING", :capacity=>3, :price=>122, venue_id: venue1.id })
# campsite36 = Campsite.create({:name=>"Candlestick RV Park", :lat=>37.7157532, :lng=>-122.383352, :campsite_type=>"RV", :capacity=>4, :price=>60, venue_id: venue2.id })
# campsite37 = Campsite.create({:name=>"Treasure Island RV Park", :lat=>37.6669269, :lng=>-122.4506284, :campsite_type=>"RV", :capacity=>19, :price=>174, venue_id: venue2.id })
# campsite38 = Campsite.create({:name=>"San Francisco RV Resort", :lat=>37.646231, :lng=>-122.492206, :campsite_type=>"RV", :capacity=>12, :price=>131, venue_id: venue2.id })
# campsite39 = Campsite.create({:name=>"Outdoorsy", :lat=>37.7719003, :lng=>-122.4134771, :campsite_type=>"RV", :capacity=>16, :price=>184, venue_id: venue2.id })
# campsite40 = Campsite.create({:name=>"Marin RV Park", :lat=>37.9404146, :lng=>-122.5139712, :campsite_type=>"RV", :capacity=>11, :price=>162, venue_id: venue2.id })
# campsite41 = Campsite.create({:name=>"Rob Hill Campground", :lat=>37.79667269999999, :lng=>-122.4758376, :campsite_type=>"RV", :capacity=>6, :price=>181, venue_id: venue2.id })
# campsite42 = Campsite.create({:name=>"RV Park of San Rafael California", :lat=>37.9626658, :lng=>-122.5118413, :campsite_type=>"RV", :capacity=>11, :price=>151, venue_id: venue2.id })
# campsite43 = Campsite.create({:name=>"Golden Gate Trailer Park", :lat=>37.9366667, :lng=>-122.5154175, :campsite_type=>"RV", :capacity=>14, :price=>173, venue_id: venue2.id })
# campsite44 = Campsite.create({:name=>"The Franciscan Park", :lat=>37.6886009, :lng=>-122.4511618, :campsite_type=>"RV", :capacity=>10, :price=>132, venue_id: venue2.id })
# campsite45 = Campsite.create({:name=>"Trailer Haven Mobile Home & RV Park", :lat=>37.7159947, :lng=>-122.1460405, :campsite_type=>"RV", :capacity=>16, :price=>116, venue_id: venue2.id })
# campsite46 = Campsite.create({:name=>"MHP Treasure Island", :lat=>37.6669031, :lng=>-122.450763, :campsite_type=>"RV", :capacity=>16, :price=>88, venue_id: venue2.id })
# campsite47 = Campsite.create({:name=>"Sierra Point Trailer Park", :lat=>37.6799235, :lng=>-122.3947548, :campsite_type=>"RV", :capacity=>6, :price=>122, venue_id: venue2.id })
# campsite48 = Campsite.create({:name=>"Pillar Point RV Park", :lat=>37.5012806, :lng=>-122.4721, :campsite_type=>"RV", :capacity=>8, :price=>182, venue_id: venue2.id })
# campsite49 = Campsite.create({:name=>"Camp Ida Smith", :lat=>37.712382, :lng=>-122.4847571, :campsite_type=>"RV", :capacity=>16, :price=>125, venue_id: venue2.id })
# campsite50 = Campsite.create({:name=>"Novato RV Park", :lat=>38.1159669, :lng=>-122.5638638, :campsite_type=>"RV", :capacity=>1, :price=>71, venue_id: venue2.id })
# campsite51 = Campsite.create({:name=>"Alpine Moblie Home Park", :lat=>37.9579713, :lng=>-122.3484802, :campsite_type=>"RV", :capacity=>8, :price=>71, venue_id: venue2.id })
# campsite52 = Campsite.create({:name=>"Sandev Mobile Home Park", :lat=>37.6787427, :lng=>-122.1568859, :campsite_type=>"RV", :capacity=>10, :price=>97, venue_id: venue2.id })
# campsite53 = Campsite.create({:name=>"Presidio Park Archives & Records Center", :lat=>37.8014754, :lng=>-122.4663394, :campsite_type=>"RV", :capacity=>11, :price=>115, venue_id: venue2.id })
# campsite54 = Campsite.create({:name=>"Tradewinds RV Park", :lat=>38.0866575, :lng=>-122.2333823, :campsite_type=>"RV", :capacity=>7, :price=>73, venue_id: venue2.id })
# campsite55 = Campsite.create({:name=>"Pelican Point RV Park", :lat=>37.4297469, :lng=>-122.4355074, :campsite_type=>"RV", :capacity=>6, :price=>111, venue_id: venue2.id })
# campsite56 = Campsite.create({:name=>"Moraine Park Campground", :lat=>40.3602146, :lng=>-105.6044912, :campsite_type=>"CAMPING", :capacity=>19, :price=>361, venue_id: venue3.id })
# campsite57 = Campsite.create({:name=>"Glacier Basin Campground", :lat=>40.3284719, :lng=>-105.5960975, :campsite_type=>"CAMPING", :capacity=>10, :price=>324, venue_id: venue3.id })
# campsite58 = Campsite.create({:name=>"Aspen Glen Campground", :lat=>40.40030590000001, :lng=>-105.5926897, :campsite_type=>"CAMPING", :capacity=>10, :price=>288, venue_id: venue3.id })
# campsite59 = Campsite.create({:name=>"Boulder Mountain Resort | Cabins - RV Sites - Tenting - Sledding - Glamping", :lat=>50.9916131, :lng=>-118.2632571, :campsite_type=>"CAMPING", :capacity=>3, :price=>195, venue_id: venue3.id })
# campsite60 = Campsite.create({:name=>"Ponderosa Campground", :lat=>44.51833329999999, :lng=>-109.0736111, :campsite_type=>"CAMPING", :capacity=>20, :price=>271, venue_id: venue3.id })
# campsite61 = Campsite.create({:name=>"Lizard Creek Campground", :lat=>44.0040604, :lng=>-110.6884271, :campsite_type=>"CAMPING", :capacity=>7, :price=>320, venue_id: venue3.id })
# campsite62 = Campsite.create({:name=>"Canyon Campground", :lat=>44.7354251, :lng=>-110.4880816, :campsite_type=>"CAMPING", :capacity=>2, :price=>234, venue_id: venue3.id })
# campsite63 = Campsite.create({:name=>"Lolo Hot Springs", :lat=>46.72478599999999, :lng=>-114.5332431, :campsite_type=>"CAMPING", :capacity=>13, :price=>283, venue_id: venue3.id })
# campsite64 = Campsite.create({:name=>"Yogi Bear's Jellystone Park™ Camp-Resort in Estes Park, CO", :lat=>40.340401, :lng=>-105.43078, :campsite_type=>"CAMPING", :capacity=>14, :price=>188, venue_id: venue3.id })
# campsite65 = Campsite.create({:name=>"Funstays LLC", :lat=>38.522372, :lng=>-109.4891718, :campsite_type=>"CAMPING", :capacity=>9, :price=>132, venue_id: venue3.id })
# campsite66 = Campsite.create({:name=>"LoneDuck Campground", :lat=>38.91766670000001, :lng=>-104.9847167, :campsite_type=>"CAMPING", :capacity=>14, :price=>222, venue_id: venue3.id })
# campsite67 = Campsite.create({:name=>"Signal Mountain Campground", :lat=>43.840768, :lng=>-110.615209, :campsite_type=>"CAMPING", :capacity=>10, :price=>227, venue_id: venue3.id })
# campsite68 = Campsite.create({:name=>"Lava Hot Springs East KOA Holiday", :lat=>42.62034149999999, :lng=>-112.0003809, :campsite_type=>"CAMPING", :capacity=>7, :price=>279, venue_id: venue3.id })
# campsite69 = Campsite.create({:name=>"Difficult Campground", :lat=>39.1413774, :lng=>-106.7739261, :campsite_type=>"CAMPING", :capacity=>17, :price=>329, venue_id: venue3.id })
# campsite70 = Campsite.create({:name=>"OK RV Park", :lat=>38.5231886, :lng=>-109.4893109, :campsite_type=>"CAMPING", :capacity=>8, :price=>391, venue_id: venue3.id })
# campsite71 = Campsite.create({:name=>"Coronado Campground", :lat=>35.3245639, :lng=>-106.5585912, :campsite_type=>"CAMPING", :capacity=>18, :price=>341, venue_id: venue3.id })
# campsite72 = Campsite.create({:name=>"Elk Creek Campground & RV Park", :lat=>40.2559392, :lng=>-105.8418731, :campsite_type=>"CAMPING", :capacity=>1, :price=>352, venue_id: venue3.id })
# campsite73 = Campsite.create({:name=>"BJ's Campground", :lat=>42.754038, :lng=>-104.44775, :campsite_type=>"CAMPING", :capacity=>15, :price=>255, venue_id: venue3.id })
# campsite74 = Campsite.create({:name=>"Estes Park Campground at Mary's Lake", :lat=>40.347043, :lng=>-105.5321, :campsite_type=>"CAMPING", :capacity=>20, :price=>223, venue_id: venue3.id })
# campsite75 = Campsite.create({:name=>"Chatfield State Park Campground", :lat=>39.5379421, :lng=>-105.064972, :campsite_type=>"CAMPING", :capacity=>3, :price=>115, venue_id: venue3.id })
# campsite76 = Campsite.create({:name=>"Rancho Los Laureles", :lat=>19.3383494, :lng=>-99.2934981, :campsite_type=>"CAMPING", :capacity=>5, :price=>26, venue_id: venue4.id })
# campsite77 = Campsite.create({:name=>"Los Dinamos II", :lat=>19.2716649, :lng=>-99.2798595, :campsite_type=>"CAMPING", :capacity=>18, :price=>50, venue_id: venue4.id })
# campsite78 = Campsite.create({:name=>"Estacionamiento Dinamos", :lat=>19.2983027, :lng=>-99.2522726, :campsite_type=>"CAMPING", :capacity=>2, :price=>117, venue_id: venue4.id })
# campsite79 = Campsite.create({:name=>"Bosque de Chapultepec", :lat=>19.4194815, :lng=>-99.18945579999999, :campsite_type=>"CAMPING", :capacity=>12, :price=>34, venue_id: venue4.id })
# campsite80 = Campsite.create({:name=>"Icaros Campamentos", :lat=>19.4875024, :lng=>-99.2512544, :campsite_type=>"CAMPING", :capacity=>10, :price=>104, venue_id: venue4.id })
# campsite81 = Campsite.create({:name=>"San Nicolás Totolapan Ejido Park", :lat=>19.2535069, :lng=>-99.2448563, :campsite_type=>"CAMPING", :capacity=>18, :price=>88, venue_id: venue4.id })
# campsite82 = Campsite.create({:name=>"Alameda Central", :lat=>19.4357353, :lng=>-99.1439486, :campsite_type=>"CAMPING", :capacity=>18, :price=>66, venue_id: venue4.id })
# campsite83 = Campsite.create({:name=>"Hampton Inn and Suites Mexico City Centro Historico", :lat=>19.4300318, :lng=>-99.13450600000002, :campsite_type=>"CAMPING", :capacity=>15, :price=>113, venue_id: venue4.id })
# campsite84 = Campsite.create({:name=>"PENSION AUTOMOTRIZ 24HRS", :lat=>19.3954701, :lng=>-99.1921096, :campsite_type=>"CAMPING", :capacity=>2, :price=>21, venue_id: venue4.id })
# campsite85 = Campsite.create({:name=>"Condesa Haus", :lat=>19.4105301, :lng=>-99.17719869999999, :campsite_type=>"CAMPING", :capacity=>4, :price=>113, venue_id: venue4.id })
# campsite86 = Campsite.create({:name=>"ESTACIONAMIENTO PUBLICO", :lat=>19.4061397, :lng=>-99.18386749999999, :campsite_type=>"CAMPING", :capacity=>8, :price=>43, venue_id: venue4.id })
# campsite87 = Campsite.create({:name=>"ESTACIONAMIENTO PUBLICO", :lat=>19.4033091, :lng=>-99.18030209999999, :campsite_type=>"CAMPING", :capacity=>16, :price=>38, venue_id: venue4.id })
# campsite88 = Campsite.create({:name=>"Los Dinamos", :lat=>19.298279, :lng=>-99.2528348, :campsite_type=>"CAMPING", :capacity=>6, :price=>35, venue_id: venue4.id })
# campsite89 = Campsite.create({:name=>"Fairfield Inn & Suites by Marriott Mexico City Vallejo", :lat=>19.4873786, :lng=>-99.15224959999999, :campsite_type=>"CAMPING", :capacity=>16, :price=>69, venue_id: venue4.id })
# campsite90 = Campsite.create({:name=>"Trailer Park Teotihuacan", :lat=>19.6830993, :lng=>-98.8706201, :campsite_type=>"CAMPING", :capacity=>7, :price=>25, venue_id: venue4.id })
# campsite91 = Campsite.create({:name=>"Hilton Mexico City Reforma", :lat=>19.4345141, :lng=>-99.14622059999999, :campsite_type=>"CAMPING", :capacity=>7, :price=>67, venue_id: venue4.id })
# campsite92 = Campsite.create({:name=>"Jardín Botánico del Bosque de Chapultepec", :lat=>19.4232698, :lng=>-99.1825593, :campsite_type=>"CAMPING", :capacity=>18, :price=>72, venue_id: venue4.id })
# campsite93 = Campsite.create({:name=>"Grupo IV Scouts de México", :lat=>19.4626325, :lng=>-99.1373569, :campsite_type=>"CAMPING", :capacity=>5, :price=>42, venue_id: venue4.id })
# campsite94 = Campsite.create({:name=>"Four Seasons Hotel Mexico City", :lat=>19.4229885, :lng=>-99.1742445, :campsite_type=>"CAMPING", :capacity=>18, :price=>117, venue_id: venue4.id })
# campsite95 = Campsite.create({:name=>"Fiesta Americana Reforma", :lat=>19.432281, :lng=>-99.1547143, :campsite_type=>"CAMPING", :capacity=>17, :price=>116, venue_id: venue4.id })
# campsite96 = Campsite.create({:name=>"Mirador LLactapata Machu Picchu", :lat=>-13.1850891, :lng=>-72.5811564, :campsite_type=>"CAMPING", :capacity=>18, :price=>310, venue_id: venue5.id })
# campsite97 = Campsite.create({:name=>"Llactapata Camping - Mirador de Machu Picchu", :lat=>-13.1857467, :lng=>-72.5813687, :campsite_type=>"CAMPING", :capacity=>1, :price=>303, venue_id: venue5.id })
# campsite98 = Campsite.create({:name=>"Municipal Camping", :lat=>-13.1620661, :lng=>-72.5348315, :campsite_type=>"CAMPING", :capacity=>6, :price=>503, venue_id: venue5.id })
# campsite99 = Campsite.create({:name=>"Mandor Camp", :lat=>-13.1491627, :lng=>-72.5392986, :campsite_type=>"CAMPING", :capacity=>19, :price=>210, venue_id: venue5.id })
# campsite100 = Campsite.create({:name=>"Belmond Sanctuary Lodge", :lat=>-13.1660699, :lng=>-72.5429408, :campsite_type=>"CAMPING", :capacity=>2, :price=>309, venue_id: venue5.id })
# campsite101 = Campsite.create({:name=>"Los Jardines de Mandor", :lat=>-13.1485797, :lng=>-72.53987409999999, :campsite_type=>"CAMPING", :capacity=>4, :price=>205, venue_id: venue5.id })
# campsite102 = Campsite.create({:name=>"Winay Wayna Camp", :lat=>-13.1902182, :lng=>-72.537623, :campsite_type=>"CAMPING", :capacity=>20, :price=>500, venue_id: venue5.id })
# campsite103 = Campsite.create({:name=>"Machu Picchu", :lat=>-13.1631412, :lng=>-72.5449629, :campsite_type=>"CAMPING", :capacity=>2, :price=>278, venue_id: venue5.id })
# campsite104 = Campsite.create({:name=>"Panorama B&B", :lat=>-13.1541727, :lng=>-72.5274541, :campsite_type=>"CAMPING", :capacity=>14, :price=>444, venue_id: venue5.id })
# campsite105 = Campsite.create({:name=>"Inkaterra Machu Picchu Pueblo Hotel", :lat=>-13.157767, :lng=>-72.522652, :campsite_type=>"CAMPING", :capacity=>3, :price=>570, venue_id: venue5.id })
# campsite106 = Campsite.create({:name=>"Jungle Domes", :lat=>-13.2142785, :lng=>-72.61868609999999, :campsite_type=>"CAMPING", :capacity=>20, :price=>382, venue_id: venue5.id })
# campsite107 = Campsite.create({:name=>"Ecopackers hostel", :lat=>-13.1539925, :lng=>-72.5265926, :campsite_type=>"CAMPING", :capacity=>6, :price=>357, venue_id: venue5.id })
# campsite108 = Campsite.create({:name=>"El MaPi Hotel byInkaterra", :lat=>-13.154373, :lng=>-72.52466299999999, :campsite_type=>"CAMPING", :capacity=>17, :price=>534, venue_id: venue5.id })
# campsite109 = Campsite.create({:name=>"Wayllabamba Camp", :lat=>-13.2642676, :lng=>-72.4470395, :campsite_type=>"CAMPING", :capacity=>3, :price=>293, venue_id: venue5.id })
# campsite110 = Campsite.create({:name=>"Andean Huts Salkantay Trekking", :lat=>-13.3249864, :lng=>-72.66510509999999, :campsite_type=>"CAMPING", :capacity=>16, :price=>282, venue_id: venue5.id })
# campsite111 = Campsite.create({:name=>"Terrazas Del Inca Bed and Breakfast en Machupicchu", :lat=>-13.1541693, :lng=>-72.52335169999999, :campsite_type=>"CAMPING", :capacity=>19, :price=>137, venue_id: venue5.id })
# campsite112 = Campsite.create({:name=>"Mesa Pata Inca Observatory and Camping", :lat=>-13.184422, :lng=>-72.5888556, :campsite_type=>"CAMPING", :capacity=>11, :price=>480, venue_id: venue5.id })
# campsite113 = Campsite.create({:name=>"KM 82", :lat=>-13.2153129, :lng=>-72.3838734, :campsite_type=>"CAMPING", :capacity=>2, :price=>397, venue_id: venue5.id })
# campsite114 = Campsite.create({:name=>"Campamento de Ayapata", :lat=>-13.2585201, :lng=>-72.46129839999999, :campsite_type=>"CAMPING", :capacity=>11, :price=>369, venue_id: venue5.id })
# campsite115 = Campsite.create({:name=>"Pirwa Hostel Machu Picchu", :lat=>-13.153976, :lng=>-72.52382360000001, :campsite_type=>"CAMPING", :capacity=>7, :price=>253, venue_id: venue5.id })
# campsite116 = Campsite.create({:name=>"Hatonosu Garden Campsite", :lat=>35.807769, :lng=>139.134937, :campsite_type=>"CAMPING", :capacity=>4, :price=>91, venue_id: venue6.id })
# campsite117 = Campsite.create({:name=>"Hikawa Camping Ground", :lat=>35.807079, :lng=>139.098902, :campsite_type=>"CAMPING", :capacity=>18, :price=>99, venue_id: venue6.id })
# campsite118 = Campsite.create({:name=>"Sakai canyon campsite", :lat=>35.800491, :lng=>139.08141, :campsite_type=>"CAMPING", :capacity=>6, :price=>72, venue_id: venue6.id })
# campsite119 = Campsite.create({:name=>"Hyakkenjaya Camping Ground", :lat=>35.847382, :lng=>139.154085, :campsite_type=>"CAMPING", :capacity=>5, :price=>128, venue_id: venue6.id })
# campsite120 = Campsite.create({:name=>"CAZU campsite", :lat=>35.8507107, :lng=>139.201731, :campsite_type=>"CAMPING", :capacity=>2, :price=>149, venue_id: venue6.id })
# campsite121 = Campsite.create({:name=>"Yamanofurusatomura Camping Ground", :lat=>35.7614522, :lng=>139.0260963, :campsite_type=>"CAMPING", :capacity=>9, :price=>176, venue_id: venue6.id })
# campsite122 = Campsite.create({:name=>"Kawai Camping Ground", :lat=>35.8115696, :lng=>139.1649289, :campsite_type=>"CAMPING", :capacity=>5, :price=>117, venue_id: venue6.id })
# campsite123 = Campsite.create({:name=>"大岳キャンプ場 下流サイト", :lat=>35.762545, :lng=>139.1580034, :campsite_type=>"CAMPING", :capacity=>19, :price=>116, venue_id: venue6.id })
# campsite124 = Campsite.create({:name=>"Mino Ishidaki campsite & Sagamiko Canoe School", :lat=>35.6020895, :lng=>139.1941751, :campsite_type=>"CAMPING", :capacity=>2, :price=>144, venue_id: venue6.id })
# campsite125 = Campsite.create({:name=>"Karasawa campsite", :lat=>35.487765, :lng=>139.221694, :campsite_type=>"CAMPING", :capacity=>1, :price=>150, venue_id: venue6.id })
# campsite126 = Campsite.create({:name=>"Dainichikogen Camping Ground", :lat=>35.9091963, :lng=>139.0860791, :campsite_type=>"CAMPING", :capacity=>20, :price=>149, venue_id: venue6.id })
# campsite127 = Campsite.create({:name=>"Seitoen Camping Ground", :lat=>35.8436561, :lng=>139.153868, :campsite_type=>"CAMPING", :capacity=>10, :price=>35, venue_id: venue6.id })
# campsite128 = Campsite.create({:name=>"Midori to taiyo campsite", :lat=>35.5762244, :lng=>139.0993435, :campsite_type=>"CAMPING", :capacity=>20, :price=>41, venue_id: venue6.id })
# campsite129 = Campsite.create({:name=>"Nakachaya Camping Ground", :lat=>35.845883, :lng=>139.152821, :campsite_type=>"CAMPING", :capacity=>19, :price=>153, venue_id: venue6.id })
# campsite130 = Campsite.create({:name=>"Hachiojishi Kodomo Camping Ground", :lat=>35.6836176, :lng=>139.2807013, :campsite_type=>"CAMPING", :capacity=>16, :price=>76, venue_id: venue6.id })
# campsite131 = Campsite.create({:name=>"Kanotoen Camping Ground", :lat=>35.7504784, :lng=>139.115724, :campsite_type=>"CAMPING", :capacity=>1, :price=>65, venue_id: venue6.id })
# campsite132 = Campsite.create({:name=>"Okutama Glamping", :lat=>35.8154553, :lng=>139.1404136, :campsite_type=>"CAMPING", :capacity=>18, :price=>175, venue_id: venue6.id })
# campsite133 = Campsite.create({:name=>"Mizunesawa Camping Ground", :lat=>35.7961659, :lng=>139.0430338, :campsite_type=>"CAMPING", :capacity=>8, :price=>34, venue_id: venue6.id })
# campsite134 = Campsite.create({:name=>"Kannogawa Camping Ground", :lat=>35.5285606, :lng=>139.1078949, :campsite_type=>"CAMPING", :capacity=>11, :price=>62, venue_id: venue6.id })
# campsite135 = Campsite.create({:name=>"Chojayashiki Camping Ground", :lat=>35.4980138, :lng=>139.2262436, :campsite_type=>"CAMPING", :capacity=>4, :price=>155, venue_id: venue6.id })
# campsite136 = Campsite.create({:name=>"Motosuko Camping Ground", :lat=>35.457526, :lng=>138.6007207, :campsite_type=>"CAMPING", :capacity=>17, :price=>58, venue_id: venue7.id })
# campsite137 = Campsite.create({:name=>"Koan Camping Ground", :lat=>35.473183, :lng=>138.574764, :campsite_type=>"CAMPING", :capacity=>11, :price=>259, venue_id: venue7.id })
# campsite138 = Campsite.create({:name=>"Motosu Lakeside Campground", :lat=>35.47673899999999, :lng=>138.592984, :campsite_type=>"CAMPING", :capacity=>11, :price=>170, venue_id: venue7.id })
# campsite139 = Campsite.create({:name=>"Suzusankyuyorin Camping Ground", :lat=>35.1952345, :lng=>138.7718941, :campsite_type=>"CAMPING", :capacity=>6, :price=>63, venue_id: venue7.id })
# campsite140 = Campsite.create({:name=>"Table Fuji camping field", :lat=>35.3121286, :lng=>138.5978936, :campsite_type=>"CAMPING", :capacity=>2, :price=>222, venue_id: venue7.id })
# campsite141 = Campsite.create({:name=>"Fumotoppara Camping Grounds", :lat=>35.4008408, :lng=>138.5611572, :campsite_type=>"CAMPING", :capacity=>9, :price=>62, venue_id: venue7.id })
# campsite142 = Campsite.create({:name=>"Tsuhara Camping Ground", :lat=>35.49897300000001, :lng=>138.698817, :campsite_type=>"CAMPING", :capacity=>3, :price=>40, venue_id: venue7.id })
# campsite143 = Campsite.create({:name=>"Kawaguchi-machi New bridge campground", :lat=>35.5097656, :lng=>138.7619084, :campsite_type=>"CAMPING", :capacity=>20, :price=>241, venue_id: venue7.id })
# campsite144 = Campsite.create({:name=>"Paseo Ashiwada Camping Ground", :lat=>35.5008549, :lng=>138.7268161, :campsite_type=>"CAMPING", :capacity=>11, :price=>119, venue_id: venue7.id })
# campsite145 = Campsite.create({:name=>"Kozanso Camping Ground", :lat=>35.412978, :lng=>138.892267, :campsite_type=>"CAMPING", :capacity=>12, :price=>59, venue_id: venue7.id })
# campsite146 = Campsite.create({:name=>"Kangakuen Camping Ground", :lat=>35.503047, :lng=>138.682055, :campsite_type=>"CAMPING", :capacity=>19, :price=>263, venue_id: venue7.id })
# campsite147 = Campsite.create({:name=>"Misaki Camping Ground", :lat=>35.423307, :lng=>138.89445, :campsite_type=>"CAMPING", :capacity=>2, :price=>74, venue_id: venue7.id })
# campsite148 = Campsite.create({:name=>"Sonei Yamanakako Camping Ground", :lat=>35.4043419, :lng=>138.8690238, :campsite_type=>"CAMPING", :capacity=>3, :price=>42, venue_id: venue7.id })
# campsite149 = Campsite.create({:name=>"SUMIKA CAMP FIELD", :lat=>35.4521112, :lng=>138.5987943, :campsite_type=>"CAMPING", :capacity=>5, :price=>69, venue_id: venue7.id })
# campsite150 = Campsite.create({:name=>"Fujimiso Camping Ground", :lat=>35.4105528, :lng=>138.8577033, :campsite_type=>"CAMPING", :capacity=>20, :price=>247, venue_id: venue7.id })
# campsite151 = Campsite.create({:name=>"Country Bear family campsite", :lat=>35.2476196, :lng=>138.8692663, :campsite_type=>"CAMPING", :capacity=>3, :price=>121, venue_id: venue7.id })
# campsite152 = Campsite.create({:name=>"PICA表富士", :lat=>35.2975863, :lng=>138.7012242, :campsite_type=>"CAMPING", :capacity=>13, :price=>108, venue_id: venue7.id })
# campsite153 = Campsite.create({:name=>"PICA Fujiyama", :lat=>35.4556786, :lng=>138.7552827, :campsite_type=>"CAMPING", :capacity=>4, :price=>262, venue_id: venue7.id })
# campsite154 = Campsite.create({:name=>"Shojikojiyu Camping Ground", :lat=>35.4860276, :lng=>138.6047233, :campsite_type=>"CAMPING", :capacity=>7, :price=>274, venue_id: venue7.id })
# campsite155 = Campsite.create({:name=>"Jiyu Camping Ground", :lat=>35.5028544, :lng=>138.684351, :campsite_type=>"CAMPING", :capacity=>15, :price=>178, venue_id: venue7.id })
# campsite156 = Campsite.create({:name=>"Camping 3 Estrellas", :lat=>41.272316, :lng=>2.0427918, :campsite_type=>"CAMPING", :capacity=>16, :price=>126, venue_id: venue8.id })
# campsite157 = Campsite.create({:name=>"Camping Boutique", :lat=>41.3925738, :lng=>2.1729103, :campsite_type=>"CAMPING", :capacity=>19, :price=>161, venue_id: venue8.id })
# campsite158 = Campsite.create({:name=>"Instalaciones Turísticas Cadaqués S.A", :lat=>41.3912526, :lng=>2.1692729, :campsite_type=>"CAMPING", :capacity=>10, :price=>199, venue_id: venue8.id })
# campsite159 = Campsite.create({:name=>"Camping Masnou", :lat=>41.4753526, :lng=>2.3039612, :campsite_type=>"CAMPING", :capacity=>19, :price=>66, venue_id: venue8.id })
# campsite160 = Campsite.create({:name=>"Camping BARCELONA", :lat=>41.55099999999999, :lng=>2.4836, :campsite_type=>"CAMPING", :capacity=>3, :price=>143, venue_id: venue8.id })
# campsite161 = Campsite.create({:name=>"Iniciativas Turísticas S A", :lat=>41.4073436, :lng=>2.1356762, :campsite_type=>"CAMPING", :capacity=>12, :price=>197, venue_id: venue8.id })
# campsite162 = Campsite.create({:name=>"Vilanova Park", :lat=>41.2320253, :lng=>1.6928816, :campsite_type=>"CAMPING", :capacity=>11, :price=>143, venue_id: venue8.id })
# campsite163 = Campsite.create({:name=>"Camping Estrella de Mar", :lat=>41.2698319, :lng=>1.9992676, :campsite_type=>"CAMPING", :capacity=>20, :price=>105, venue_id: venue8.id })
# campsite164 = Campsite.create({:name=>"Camping Globo Rojo Barcelona", :lat=>41.5913202, :lng=>2.5917749, :campsite_type=>"CAMPING", :capacity=>6, :price=>30, venue_id: venue8.id })
# campsite165 = Campsite.create({:name=>"Camping Enmar", :lat=>41.6217773, :lng=>2.6859453, :campsite_type=>"CAMPING", :capacity=>3, :price=>155, venue_id: venue8.id })
# campsite166 = Campsite.create({:name=>"Thelis UnixData SL", :lat=>41.3809846, :lng=>2.155327, :campsite_type=>"CAMPING", :capacity=>12, :price=>77, venue_id: venue8.id })
# campsite167 = Campsite.create({:name=>"Camping Sitges", :lat=>41.23206640000001, :lng=>1.7849414, :campsite_type=>"CAMPING", :capacity=>4, :price=>42, venue_id: venue8.id })
# campsite168 = Campsite.create({:name=>"Camping Bellsol", :lat=>41.619099, :lng=>2.6791795, :campsite_type=>"CAMPING", :capacity=>15, :price=>50, venue_id: venue8.id })
# campsite169 = Campsite.create({:name=>"Gremi de Garatge", :lat=>41.377396, :lng=>2.1779232, :campsite_type=>"CAMPING", :capacity=>20, :price=>125, venue_id: venue8.id })
# campsite170 = Campsite.create({:name=>"Camping El Garrofer", :lat=>41.2333765, :lng=>1.7810992, :campsite_type=>"CAMPING", :capacity=>15, :price=>195, venue_id: venue8.id })
# campsite171 = Campsite.create({:name=>"Camping Resort Els Pins", :lat=>41.648083, :lng=>2.769975, :campsite_type=>"CAMPING", :capacity=>3, :price=>170, venue_id: venue8.id })
# campsite172 = Campsite.create({:name=>"El Vedado", :lat=>41.5234158, :lng=>2.2937796, :campsite_type=>"CAMPING", :capacity=>17, :price=>178, venue_id: venue8.id })
# campsite173 = Campsite.create({:name=>"Montserrat Campsite", :lat=>41.5907663, :lng=>1.8382486, :campsite_type=>"CAMPING", :capacity=>5, :price=>127, venue_id: venue8.id })
# campsite174 = Campsite.create({:name=>"Parking Camping Montmeló", :lat=>41.5652398, :lng=>2.2514141, :campsite_type=>"CAMPING", :capacity=>19, :price=>51, venue_id: venue8.id })
# campsite175 = Campsite.create({:name=>"CAMPING MARCOS", :lat=>41.583834, :lng=>2.568336, :campsite_type=>"CAMPING", :capacity=>8, :price=>191, venue_id: venue8.id })
# campsite176 = Campsite.create({:name=>"Camac Valley Tourist Caravan and Camping Park", :lat=>53.304666, :lng=>-6.415259499999999, :campsite_type=>"GLAMPING", :capacity=>1, :price=>106, venue_id: venue9.id })
# campsite177 = Campsite.create({:name=>"Lynders Mobile Home Park", :lat=>53.4911705, :lng=>-6.0992589, :campsite_type=>"GLAMPING", :capacity=>17, :price=>208, venue_id: venue9.id })
# campsite178 = Campsite.create({:name=>"WoofAdvisor", :lat=>53.3492356, :lng=>-6.247738099999999, :campsite_type=>"GLAMPING", :capacity=>1, :price=>273, venue_id: venue9.id })
# campsite179 = Campsite.create({:name=>"Scouting Ireland, Larch Hill", :lat=>53.25440469999999, :lng=>-6.2838132, :campsite_type=>"GLAMPING", :capacity=>2, :price=>85, venue_id: venue9.id })
# campsite180 = Campsite.create({:name=>"Camper Park Dublin", :lat=>53.4413874, :lng=>-6.336420899999999, :campsite_type=>"GLAMPING", :capacity=>20, :price=>199, venue_id: venue9.id })
# campsite181 = Campsite.create({:name=>"Glendalough Glamping", :lat=>53.0119218, :lng=>-6.296375599999999, :campsite_type=>"GLAMPING", :capacity=>12, :price=>288, venue_id: venue9.id })
# campsite182 = Campsite.create({:name=>"Corkagh Park", :lat=>53.3113286, :lng=>-6.4120235, :campsite_type=>"GLAMPING", :capacity=>13, :price=>149, venue_id: venue9.id })
# campsite183 = Campsite.create({:name=>"Knockrobin Glamping", :lat=>52.997448, :lng=>-6.068008, :campsite_type=>"GLAMPING", :capacity=>19, :price=>57, venue_id: venue9.id })
# campsite184 = Campsite.create({:name=>"Rock Farm Slane", :lat=>53.70441349999999, :lng=>-6.544685599999999, :campsite_type=>"GLAMPING", :capacity=>15, :price=>273, venue_id: venue9.id })
# campsite185 = Campsite.create({:name=>"Avondale Guesthouse", :lat=>53.3509259, :lng=>-6.2548264, :campsite_type=>"GLAMPING", :capacity=>8, :price=>288, venue_id: venue9.id })
# campsite186 = Campsite.create({:name=>"The Old Forge Glamping", :lat=>52.7656603, :lng=>-6.6380642, :campsite_type=>"GLAMPING", :capacity=>10, :price=>183, venue_id: venue9.id })
# campsite187 = Campsite.create({:name=>"Private Double Room in Dublin City Center", :lat=>53.35617420000001, :lng=>-6.266285799999999, :campsite_type=>"GLAMPING", :capacity=>9, :price=>104, venue_id: venue9.id })
# campsite188 = Campsite.create({:name=>"Mountjoy Square Park", :lat=>53.35663479999999, :lng=>-6.257447399999999, :campsite_type=>"GLAMPING", :capacity=>20, :price=>162, venue_id: venue9.id })
# campsite189 = Campsite.create({:name=>"Vicar Street Apartments", :lat=>53.3431432, :lng=>-6.2803425, :campsite_type=>"GLAMPING", :capacity=>16, :price=>291, venue_id: venue9.id })
# campsite190 = Campsite.create({:name=>"Homelink Home Exchange", :lat=>53.43584, :lng=>-6.130216, :campsite_type=>"GLAMPING", :capacity=>14, :price=>108, venue_id: venue9.id })
# campsite191 = Campsite.create({:name=>"Hidden Valley Holiday Park", :lat=>52.939144, :lng=>-6.227361, :campsite_type=>"GLAMPING", :capacity=>18, :price=>246, venue_id: venue9.id })
# campsite192 = Campsite.create({:name=>"Glamping Under The Stars", :lat=>52.9727754, :lng=>-7.2682396, :campsite_type=>"GLAMPING", :capacity=>8, :price=>161, venue_id: venue9.id })
# campsite193 = Campsite.create({:name=>"Tibradden Farm Cottages", :lat=>53.2451421, :lng=>-6.278429, :campsite_type=>"GLAMPING", :capacity=>20, :price=>140, venue_id: venue9.id })
# campsite194 = Campsite.create({:name=>"River Valley Holiday Park", :lat=>52.88909229999999, :lng=>-6.14465, :campsite_type=>"GLAMPING", :capacity=>17, :price=>178, venue_id: venue9.id })
# campsite195 = Campsite.create({:name=>"Powerscourt House & Gardens", :lat=>53.184251, :lng=>-6.1866327, :campsite_type=>"GLAMPING", :capacity=>9, :price=>274, venue_id: venue9.id })
# campsite196 = Campsite.create({:name=>"Rocky Mountain National Park", :lat=>40.3427932, :lng=>-105.6836389, :campsite_type=>"GLAMPING", :capacity=>3, :price=>341, venue_id: venue3.id })
# campsite197 = Campsite.create({:name=>"Red Rocks Glamping", :lat=>39.6387493, :lng=>-105.1926557, :campsite_type=>"GLAMPING", :capacity=>12, :price=>322, venue_id: venue3.id })
# campsite198 = Campsite.create({:name=>"Boulder Mountain Resort | Cabins - RV Sites - Tenting - Sledding - Glamping", :lat=>50.9916131, :lng=>-118.2632571, :campsite_type=>"GLAMPING", :capacity=>16, :price=>359, venue_id: venue3.id })
# campsite199 = Campsite.create({:name=>"Collective Vail, a Retreat at 4 Eagle Ranch", :lat=>39.7499917, :lng=>-106.6721164, :campsite_type=>"GLAMPING", :capacity=>9, :price=>293, venue_id: venue3.id })
# campsite200 = Campsite.create({:name=>"Dunton River Camp", :lat=>37.737291, :lng=>-108.155059, :campsite_type=>"GLAMPING", :capacity=>2, :price=>364, venue_id: venue3.id })
# campsite201 = Campsite.create({:name=>"The Evergreens On Fall River Cabins", :lat=>40.3961157, :lng=>-105.5661086, :campsite_type=>"GLAMPING", :capacity=>2, :price=>216, venue_id: venue3.id })
# campsite202 = Campsite.create({:name=>"Under Canvas Glacier", :lat=>48.4415543, :lng=>-114.0378404, :campsite_type=>"GLAMPING", :capacity=>3, :price=>199, venue_id: venue3.id })
# campsite203 = Campsite.create({:name=>"Anasazi Wilderness Glamping Cabin", :lat=>36.376895, :lng=>-106.726771, :campsite_type=>"GLAMPING", :capacity=>2, :price=>130, venue_id: venue3.id })
# campsite204 = Campsite.create({:name=>"Sundance Lodges, Kananaskis Country", :lat=>50.952526, :lng=>-115.124048, :campsite_type=>"GLAMPING", :capacity=>3, :price=>104, venue_id: venue3.id })
# campsite205 = Campsite.create({:name=>"Under Canvas Yellowstone", :lat=>44.7043217, :lng=>-111.2111627, :campsite_type=>"GLAMPING", :capacity=>15, :price=>190, venue_id: venue3.id })
# campsite206 = Campsite.create({:name=>"Grand Teton National Park", :lat=>43.7904282, :lng=>-110.6817627, :campsite_type=>"GLAMPING", :capacity=>5, :price=>285, venue_id: venue3.id })
# campsite207 = Campsite.create({:name=>"WeeCasa Tiny House Resort", :lat=>40.2254573, :lng=>-105.2739808, :campsite_type=>"GLAMPING", :capacity=>9, :price=>195, venue_id: venue3.id })
# campsite208 = Campsite.create({:name=>"Solitude Cabins-Estes Park Cabins", :lat=>40.36839920000001, :lng=>-105.4923617, :campsite_type=>"GLAMPING", :capacity=>1, :price=>178, venue_id: venue3.id })
# campsite209 = Campsite.create({:name=>"Rocky Mountain Hi Campground", :lat=>48.251373, :lng=>-114.254652, :campsite_type=>"GLAMPING", :capacity=>20, :price=>273, venue_id: venue3.id })
# campsite210 = Campsite.create({:name=>"Yellowstone National Park", :lat=>44.427963, :lng=>-110.588455, :campsite_type=>"GLAMPING", :capacity=>4, :price=>325, venue_id: venue3.id })
# campsite211 = Campsite.create({:name=>"Pike and San Isabel National Forests & Cimarron and Comanche National Grasslands", :lat=>38.6983152, :lng=>-105.8794588, :campsite_type=>"GLAMPING", :capacity=>5, :price=>379, venue_id: venue3.id })
# campsite212 = Campsite.create({:name=>"Collective Yellowstone, a Retreat at Moonlight Basin", :lat=>45.3169264, :lng=>-111.4193394, :campsite_type=>"GLAMPING", :capacity=>1, :price=>348, venue_id: venue3.id })
# campsite213 = Campsite.create({:name=>"Broadmoor Cloud Camp", :lat=>38.75882, :lng=>-104.866129, :campsite_type=>"GLAMPING", :capacity=>8, :price=>124, venue_id: venue3.id })
# campsite214 = Campsite.create({:name=>"Crandell Mountain Campground", :lat=>49.0989744, :lng=>-113.9534566, :campsite_type=>"GLAMPING", :capacity=>8, :price=>275, venue_id: venue3.id })
# campsite215 = Campsite.create({:name=>"Under Canvas Zion", :lat=>37.2682087, :lng=>-113.1147972, :campsite_type=>"GLAMPING", :capacity=>15, :price=>200, venue_id: venue3.id })

# # CREATE CATEGORY TABLE
# category1 = Category.create(name: "Amenities")
# category2 = Category.create(name: "Activities")
# category3 = Category.create(name: "Terrain")

# # CREATE TAG TABLE
# tag1 = Tag.create(name: "Pets allowed", category:"Amenities")
# tag2 = Tag.create(name: "Toilets", category:"Amenities")
# tag3 = Tag.create(name: "Campfires", category:"Amenities")
# tag4 = Tag.create(name: "Water", category:"Amenities")
# tag5 = Tag.create(name: "Showers", category:"Amenities")
# tag6 = Tag.create(name: "Picnic table", category:"Amenities")
# tag7 = Tag.create(name: "Trash", category:"Amenities")
# tag8 = Tag.create(name: "Wifi", category:"Amenities")
# tag9 = Tag.create(name: "Cooking equipment", category:"Amenities")
# tag10 = Tag.create(name: "Hiking", category:"Activities")
# tag11 = Tag.create(name: "Swimming", category:"Activities")
# tag12 = Tag.create(name: "Fishing", category:"Activities")
# tag13 = Tag.create(name: "Paddling", category:"Activities")
# tag14 = Tag.create(name: "Wildlife watching", category:"Activities")
# tag15 = Tag.create(name: "Biking", category:"Activities")
# tag16 = Tag.create(name: "Boating", category:"Activities")
# tag17 = Tag.create(name: "OHV", category:"Activities")
# tag18 = Tag.create(name: "Whitewater paddling", category:"Activities")
# tag19 = Tag.create(name: "Climbing", category:"Activities")
# tag20 = Tag.create(name: "Snow sports", category:"Activities")
# tag21 = Tag.create(name: "Horseback riding", category:"Activities")
# tag22 = Tag.create(name: "Surfing", category:"Activities")
# tag23 = Tag.create(name: "Wind sports", category:"Activities")
# tag24 = Tag.create(name: "Stargazing", category:"Activities")
# tag25 = Tag.create(name: "Lake", category:"Terrain")
# tag26 = Tag.create(name: "Beach", category:"Terrain")
# tag27 = Tag.create(name: "Forest", category:"Terrain")
# tag28 = Tag.create(name: "River, stream or creek", category:"Terrain")
# tag29 = Tag.create(name: "Hot spring", category:"Terrain")
# tag30 = Tag.create(name: "Redwoods", category:"Terrain")
# tag31 = Tag.create(name: "Swimming hole", category:"Terrain")
# tag32 = Tag.create(name: "Desert", category:"Terrain")
# tag33 = Tag.create(name: "Cave", category:"Terrain")

# # CREATE CAMPSITE TAGGING TABLE
# campsite_tagging1 = CampsiteTagging.create(campsite_id: campsite199.id, tag_id: tag14.id )
# campsite_tagging2 = CampsiteTagging.create(campsite_id: campsite205.id, tag_id: tag25.id )
# campsite_tagging3 = CampsiteTagging.create(campsite_id: campsite110.id, tag_id: tag22.id )
# campsite_tagging4 = CampsiteTagging.create(campsite_id: campsite74.id, tag_id: tag20.id )
# campsite_tagging5 = CampsiteTagging.create(campsite_id: campsite33.id, tag_id: tag26.id )
# campsite_tagging6 = CampsiteTagging.create(campsite_id: campsite100.id, tag_id: tag10.id )
# campsite_tagging7 = CampsiteTagging.create(campsite_id: campsite73.id, tag_id: tag20.id )
# campsite_tagging8 = CampsiteTagging.create(campsite_id: campsite11.id, tag_id: tag17.id )
# campsite_tagging9 = CampsiteTagging.create(campsite_id: campsite142.id, tag_id: tag12.id )
# campsite_tagging10 = CampsiteTagging.create(campsite_id: campsite182.id, tag_id: tag15.id )
# campsite_tagging11 = CampsiteTagging.create(campsite_id: campsite27.id, tag_id: tag1.id )
# campsite_tagging12 = CampsiteTagging.create(campsite_id: campsite148.id, tag_id: tag25.id )
# campsite_tagging13 = CampsiteTagging.create(campsite_id: campsite205.id, tag_id: tag14.id )
# campsite_tagging14 = CampsiteTagging.create(campsite_id: campsite208.id, tag_id: tag2.id )
# campsite_tagging15 = CampsiteTagging.create(campsite_id: campsite39.id, tag_id: tag17.id )
# campsite_tagging16 = CampsiteTagging.create(campsite_id: campsite78.id, tag_id: tag18.id )
# campsite_tagging17 = CampsiteTagging.create(campsite_id: campsite170.id, tag_id: tag18.id )
# campsite_tagging18 = CampsiteTagging.create(campsite_id: campsite21.id, tag_id: tag30.id )
# campsite_tagging19 = CampsiteTagging.create(campsite_id: campsite120.id, tag_id: tag11.id )
# campsite_tagging20 = CampsiteTagging.create(campsite_id: campsite165.id, tag_id: tag23.id )
# campsite_tagging21 = CampsiteTagging.create(campsite_id: campsite170.id, tag_id: tag3.id )
# campsite_tagging22 = CampsiteTagging.create(campsite_id: campsite2.id, tag_id: tag27.id )
# campsite_tagging23 = CampsiteTagging.create(campsite_id: campsite144.id, tag_id: tag16.id )
# campsite_tagging24 = CampsiteTagging.create(campsite_id: campsite69.id, tag_id: tag29.id )
# campsite_tagging25 = CampsiteTagging.create(campsite_id: campsite174.id, tag_id: tag31.id )
# campsite_tagging26 = CampsiteTagging.create(campsite_id: campsite110.id, tag_id: tag23.id )
# campsite_tagging27 = CampsiteTagging.create(campsite_id: campsite102.id, tag_id: tag32.id )
# campsite_tagging28 = CampsiteTagging.create(campsite_id: campsite190.id, tag_id: tag12.id )
# campsite_tagging29 = CampsiteTagging.create(campsite_id: campsite69.id, tag_id: tag22.id )
# campsite_tagging30 = CampsiteTagging.create(campsite_id: campsite132.id, tag_id: tag32.id )
# campsite_tagging31 = CampsiteTagging.create(campsite_id: campsite130.id, tag_id: tag4.id )
# campsite_tagging32 = CampsiteTagging.create(campsite_id: campsite57.id, tag_id: tag22.id )
# campsite_tagging33 = CampsiteTagging.create(campsite_id: campsite200.id, tag_id: tag33.id )
# campsite_tagging34 = CampsiteTagging.create(campsite_id: campsite36.id, tag_id: tag28.id )
# campsite_tagging35 = CampsiteTagging.create(campsite_id: campsite134.id, tag_id: tag25.id )
# campsite_tagging36 = CampsiteTagging.create(campsite_id: campsite139.id, tag_id: tag8.id )
# campsite_tagging37 = CampsiteTagging.create(campsite_id: campsite140.id, tag_id: tag13.id )
# campsite_tagging38 = CampsiteTagging.create(campsite_id: campsite5.id, tag_id: tag28.id )
# campsite_tagging39 = CampsiteTagging.create(campsite_id: campsite91.id, tag_id: tag23.id )
# campsite_tagging40 = CampsiteTagging.create(campsite_id: campsite48.id, tag_id: tag33.id )
# campsite_tagging41 = CampsiteTagging.create(campsite_id: campsite183.id, tag_id: tag11.id )
# campsite_tagging42 = CampsiteTagging.create(campsite_id: campsite206.id, tag_id: tag24.id )
# campsite_tagging43 = CampsiteTagging.create(campsite_id: campsite154.id, tag_id: tag34.id )
# campsite_tagging44 = CampsiteTagging.create(campsite_id: campsite167.id, tag_id: tag28.id )
# campsite_tagging45 = CampsiteTagging.create(campsite_id: campsite55.id, tag_id: tag6.id )
# campsite_tagging46 = CampsiteTagging.create(campsite_id: campsite116.id, tag_id: tag2.id )
# campsite_tagging47 = CampsiteTagging.create(campsite_id: campsite27.id, tag_id: tag11.id )
# campsite_tagging48 = CampsiteTagging.create(campsite_id: campsite165.id, tag_id: tag25.id )
# campsite_tagging49 = CampsiteTagging.create(campsite_id: campsite210.id, tag_id: tag9.id )
# campsite_tagging50 = CampsiteTagging.create(campsite_id: campsite33.id, tag_id: tag6.id )

# # CREATE REVIEW TABLE
# r1 = Review.create({:title=>"It is our choices, Harry, that show what we truly are, far more than our abilities.", :description=>"This particular location like the many other restaurants down the block has ample seating and a second floor.", :rating=>3 , :campsite_id=> campsite144.id , :user_id=> u25.id })
# r2 = Review.create({:title=>"It does not do to dwell on dreams and forget to live.", :description=>"Brand new. Great design. Odd to hear pop music in a Mexican establishment. Music is a bit loud. It should be background.", :rating=>2 , :campsite_id=> campsite12.id , :user_id=> u20.id })
# r3 = Review.create({:title=>"Things we lose have a way of coming back to us in the end, if not always in the way we expect.", :description=>"For dessert, we ordered the chocolate drizzled churros and they were delicious too! They even came with some fresh fruit (blueberries and strawberries).", :rating=>4 , :campsite_id=> campsite52.id , :user_id=> u29.id })
# r4 = Review.create({:title=>"It does not do to dwell on dreams and forget to live.", :description=>"Brand new. Great design. Odd to hear pop music in a Mexican establishment. Music is a bit loud. It should be background.", :rating=>2 , :campsite_id=> campsite90.id , :user_id=> u11.id })
# r5 = Review.create({:title=>"I solemnly swear that I am up to no good.", :description=>"My only critique would be that the rice could of used more vingaer and for them to use real wasabi. Also the variety of fish in stock wasnt a lot but hopefully that can change over time. The cost justify the quality youre getting. A solid 4 stars.", :rating=>1 , :campsite_id=> campsite96.id , :user_id=> u28.id })
# r6 = Review.create({:title=>"Just because you have the emotional range of a teaspoon doesn’t mean we all have.", :description=>"In terms of omakase, they had a few options but the one we chose was the 87 dollar version which include sashimi and sushi.", :rating=>1 , :campsite_id=> campsite131.id , :user_id=> u9.id })
# r7 = Review.create({:title=>"It’s wingardium leviOsa, not leviosAH.", :description=>"Staff was very accommodating but the chef were no nonsense. The ambiance is clean and tranquil which is perfect if youre looking to have a conversation with a date or a friend.", :rating=>4 , :campsite_id=> campsite174.id , :user_id=> u21.id })
# r8 = Review.create({:title=>"Dark and difficult times lie ahead. Soon we must all face the choice between what is right and what is easy.", :description=>"Great place to stop in from a chaotic Times Square adventure! The coffee is great, the drinks are creative and the staff is very nice and hospitable. Cant wait to stop in again. Without a doubt 5 stars from me!!", :rating=>4 , :campsite_id=> campsite61.id , :user_id=> u9.id })
# r9 = Review.create({:title=>"Of course it is happening inside your head, Harry, but why on earth should that mean that it is not real?", :description=>"Staff was very accommodating but the chef were no nonsense. The ambiance is clean and tranquil which is perfect if youre looking to have a conversation with a date or a friend.", :rating=>2 , :campsite_id=> campsite93.id , :user_id=> u20.id })
# r10 = Review.create({:title=>"It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.", :description=>"The chicken nachos were delicious and the atmosphere was great. The frozen margaritas were a little on the weak side. Would probably return for a work happy hour but was pretty disappointed about the lack of free tequila and beer we read about!", :rating=>3 , :campsite_id=> campsite140.id , :user_id=> u28.id })
# r11 = Review.create({:title=>"It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.", :description=>"This particular location like the many other restaurants down the block has ample seating and a second floor.", :rating=>3 , :campsite_id=> campsite60.id , :user_id=> u20.id })
# r12 = Review.create({:title=>"It is the unknown we fear when we look upon death and darkness, nothing more.", :description=>"This particular location like the many other restaurants down the block has ample seating and a second floor.", :rating=>3 , :campsite_id=> campsite151.id , :user_id=> u24.id })
# r13 = Review.create({:title=>"If you want to know what a man’s like, take a good look at how he treats his inferiors, not his equals.", :description=>"I first heard about this place through Instagram post. The drinks looked creative so I made it a point to give it try while in the city. Located inside American Eagle in Times Square they serve up the coolest non-alcoholic beverages. You have an array of options from tea, soda, coffee, latte, water and more. Theres countertops (with phone chargers) so youre able to stand and enjoy your beverage. This visit I opted for the Pegasus latte which was not only beautiful but tasted just as good as it looked. Great staff and great service. This is a must try if you are in the area. Im sure Ill be back soon!", :rating=>1 , :campsite_id=> campsite182.id , :user_id=> u3.id })
# r14 = Review.create({:title=>"Never trust anything that can think for itself if you can't see where it keeps its brain.", :description=>"Great lattes and cold drinks as well. Nice to see a place carrying local coffee and products in Times Square! Excited to make it a part of my morning commute as it is much less crowded than the chain coffee shops around here.", :rating=>3 , :campsite_id=> campsite72.id , :user_id=> u1.id })
# r15 = Review.create({:title=>"You're a wizard, Harry.", :description=>"The chicken nachos were delicious and the atmosphere was great. The frozen margaritas were a little on the weak side. Would probably return for a work happy hour but was pretty disappointed about the lack of free tequila and beer we read about!", :rating=>3 , :campsite_id=> campsite152.id , :user_id=> u5.id })
# r16 = Review.create({:title=>"If you want to know what a man’s like, take a good look at how he treats his inferiors, not his equals.", :description=>"They are way understaffed, where the cashier needs to stop taking orders to help pack to-go orders. The line ends up piling up and people are neglected.  Seen this happen multiple times during lunch hours.", :rating=>3 , :campsite_id=> campsite8.id , :user_id=> u27.id })
# r17 = Review.create({:title=>"Never trust anything that can think for itself if you can't see where it keeps its brain.", :description=>"Great place to stop in from a chaotic Times Square adventure! The coffee is great, the drinks are creative and the staff is very nice and hospitable. Cant wait to stop in again. Without a doubt 5 stars from me!!", :rating=>3 , :campsite_id=> campsite33.id , :user_id=> u29.id })
# r18 = Review.create({:title=>"Happiness can be found even in the darkest of times if only one remembers to turn on the light.", :description=>"For dinner we ordered the shrimp enchiladas, chicken enchiladas, chicken burrito, chimichangas, and steak quesadillas. Everything was so tasty and amazing. I wasnt surprised because the food at the FiDi location is the best so I figured this location would be just as good and it was!!! The enchiladas with the green sauce is to die for. My go to at the FiDi location is usually the chicken enchiladas but I decided to try something new and the shrimp enchiladas did not disappoint.", :rating=>3 , :campsite_id=> campsite194.id , :user_id=> u30.id })
# r19 = Review.create({:title=>"Harry, suffering like this proves you are still a man! This pain is part of being human...the fact that you can feel pain like this is your greatest strength.", :description=>"Brand new. Great design. Odd to hear pop music in a Mexican establishment. Music is a bit loud. It should be background.", :rating=>2 , :campsite_id=> campsite209.id , :user_id=> u3.id })
# r20 = Review.create({:title=>"Harry, suffering like this proves you are still a man! This pain is part of being human...the fact that you can feel pain like this is your greatest strength.", :description=>"I first heard about this place through Instagram post. The drinks looked creative so I made it a point to give it try while in the city. Located inside American Eagle in Times Square they serve up the coolest non-alcoholic beverages. You have an array of options from tea, soda, coffee, latte, water and more. Theres countertops (with phone chargers) so youre able to stand and enjoy your beverage. This visit I opted for the Pegasus latte which was not only beautiful but tasted just as good as it looked. Great staff and great service. This is a must try if you are in the area. Im sure Ill be back soon!", :rating=>3 , :campsite_id=> campsite168.id , :user_id=> u7.id })
# r21 = Review.create({:title=>"You sort of start thinking anything’s possible if you’ve got enough nerve.", :description=>"In terms of omakase, they had a few options but the one we chose was the 87 dollar version which include sashimi and sushi.", :rating=>5 , :campsite_id=> campsite158.id , :user_id=> u23.id })
# r22 = Review.create({:title=>"We’ve all got both light and dark inside us. What matters is the part we choose to act on. That’s who we really are.", :description=>"My only critique would be that the rice could of used more vingaer and for them to use real wasabi. Also the variety of fish in stock wasnt a lot but hopefully that can change over time. The cost justify the quality youre getting. A solid 4 stars.", :rating=>3 , :campsite_id=> campsite42.id , :user_id=> u9.id })
# r23 = Review.create({:title=>"I solemnly swear that I am up to no good.", :description=>"The counter is on the left side, and so is the menu. It can get pretty busy with 30 min wait times. I recommend checking the website and see how busy their store is.", :rating=>3 , :campsite_id=> campsite148.id , :user_id=> u3.id })
# r24 = Review.create({:title=>"Never trust anything that can think for itself if you can't see where it keeps its brain.", :description=>"They are way understaffed, where the cashier needs to stop taking orders to help pack to-go orders. The line ends up piling up and people are neglected.  Seen this happen multiple times during lunch hours.", :rating=>4 , :campsite_id=> campsite167.id , :user_id=> u4.id })
# r25 = Review.create({:title=>"Harry, suffering like this proves you are still a man! This pain is part of being human...the fact that you can feel pain like this is your greatest strength.", :description=>"Overall, the evening was a smash and I am so glad there is a new location closer to my office!!", :rating=>5 , :campsite_id=> campsite58.id , :user_id=> u15.id })
# r26 = Review.create({:title=>"It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.", :description=>"This particular location like the many other restaurants down the block has ample seating and a second floor.", :rating=>3 , :campsite_id=> campsite77.id , :user_id=> u29.id })
# r27 = Review.create({:title=>"Just because you have the emotional range of a teaspoon doesn’t mean we all have.", :description=>"For dessert, we ordered the chocolate drizzled churros and they were delicious too! They even came with some fresh fruit (blueberries and strawberries).", :rating=>3 , :campsite_id=> campsite147.id , :user_id=> u7.id })
# r28 = Review.create({:title=>"Harry, suffering like this proves you are still a man! This pain is part of being human...the fact that you can feel pain like this is your greatest strength.", :description=>"Overall, the evening was a smash and I am so glad there is a new location closer to my office!!", :rating=>3 , :campsite_id=> campsite64.id , :user_id=> u16.id })
# r29 = Review.create({:title=>"Words are in my not-so-humble opinion, the most inexhaustible form of magic we have, capable both of inflicting injury and remedying it.", :description=>"Great place to stop in from a chaotic Times Square adventure! The coffee is great, the drinks are creative and the staff is very nice and hospitable. Cant wait to stop in again. Without a doubt 5 stars from me!!", :rating=>4 , :campsite_id=> campsite76.id , :user_id=> u14.id })
# r30 = Review.create({:title=>"Just because you have the emotional range of a teaspoon doesn’t mean we all have.", :description=>"They are way understaffed, where the cashier needs to stop taking orders to help pack to-go orders. The line ends up piling up and people are neglected.  Seen this happen multiple times during lunch hours.", :rating=>3 , :campsite_id=> campsite53.id , :user_id=> u26.id })
# r31 = Review.create({:title=>"Of course it is happening inside your head, Harry, but why on earth should that mean that it is not real?", :description=>"In terms of omakase, they had a few options but the one we chose was the 87 dollar version which include sashimi and sushi.", :rating=>2 , :campsite_id=> campsite81.id , :user_id=> u17.id })
# r32 = Review.create({:title=>"Harry, suffering like this proves you are still a man! This pain is part of being human...the fact that you can feel pain like this is your greatest strength.", :description=>"Brand new. Great design. Odd to hear pop music in a Mexican establishment. Music is a bit loud. It should be background.", :rating=>3 , :campsite_id=> campsite59.id , :user_id=> u4.id })
# r33 = Review.create({:title=>"It is the unknown we fear when we look upon death and darkness, nothing more.", :description=>"Staff was very accommodating but the chef were no nonsense. The ambiance is clean and tranquil which is perfect if youre looking to have a conversation with a date or a friend.", :rating=>3 , :campsite_id=> campsite171.id , :user_id=> u9.id })
# r34 = Review.create({:title=>"If you want to know what a man’s like, take a good look at how he treats his inferiors, not his equals.", :description=>"In terms of omakase, they had a few options but the one we chose was the 87 dollar version which include sashimi and sushi.", :rating=>3 , :campsite_id=> campsite161.id , :user_id=> u11.id })
# r35 = Review.create({:title=>"Of course it is happening inside your head, Harry, but why on earth should that mean that it is not real?", :description=>"The chicken nachos were delicious and the atmosphere was great. The frozen margaritas were a little on the weak side. Would probably return for a work happy hour but was pretty disappointed about the lack of free tequila and beer we read about!", :rating=>2 , :campsite_id=> campsite79.id , :user_id=> u5.id })
# r36 = Review.create({:title=>"It is our choices, Harry, that show what we truly are, far more than our abilities.", :description=>"Staff was very accommodating but the chef were no nonsense. The ambiance is clean and tranquil which is perfect if youre looking to have a conversation with a date or a friend.", :rating=>4 , :campsite_id=> campsite29.id , :user_id=> u2.id })
# r37 = Review.create({:title=>"It’s wingardium leviOsa, not leviosAH.", :description=>"Fish was high quality but portions were small. $57 for 9 pieces and a hand roll which is fair but on the expensive side.", :rating=>3 , :campsite_id=> campsite102.id , :user_id=> u11.id })
# r38 = Review.create({:title=>"You're a wizard, Harry.", :description=>"I first heard about this place through Instagram post. The drinks looked creative so I made it a point to give it try while in the city. Located inside American Eagle in Times Square they serve up the coolest non-alcoholic beverages. You have an array of options from tea, soda, coffee, latte, water and more. Theres countertops (with phone chargers) so youre able to stand and enjoy your beverage. This visit I opted for the Pegasus latte which was not only beautiful but tasted just as good as it looked. Great staff and great service. This is a must try if you are in the area. Im sure Ill be back soon!", :rating=>4 , :campsite_id=> campsite26.id , :user_id=> u14.id })
# r39 = Review.create({:title=>"If you want to know what a man’s like, take a good look at how he treats his inferiors, not his equals.", :description=>"For dessert, we ordered the chocolate drizzled churros and they were delicious too! They even came with some fresh fruit (blueberries and strawberries).", :rating=>5 , :campsite_id=> campsite130.id , :user_id=> u25.id })
# r40 = Review.create({:title=>"After all this time? Always.", :description=>"They are way understaffed, where the cashier needs to stop taking orders to help pack to-go orders. The line ends up piling up and people are neglected.  Seen this happen multiple times during lunch hours.", :rating=>4 , :campsite_id=> campsite212.id , :user_id=> u22.id })

